//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanchoneteProvaLab.ConsoleApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LanchoneteProvaLab.ConsoleApp.Resources.en", typeof(en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register supplier.
        /// </summary>
        internal static string CadastrarFornecedor {
            get {
                return ResourceManager.GetString("CadastrarFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register product.
        /// </summary>
        internal static string CadastrarProduto {
            get {
                return ResourceManager.GetString("CadastrarProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register sale.
        /// </summary>
        internal static string CadastrarVenda {
            get {
                return ResourceManager.GetString("CadastrarVenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit supplier.
        /// </summary>
        internal static string EditarFornecedor {
            get {
                return ResourceManager.GetString("EditarFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit product.
        /// </summary>
        internal static string EditarProduto {
            get {
                return ResourceManager.GetString("EditarProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit sale.
        /// </summary>
        internal static string EditarVenda {
            get {
                return ResourceManager.GetString("EditarVenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove supplier.
        /// </summary>
        internal static string ExcluirFornecedor {
            get {
                return ResourceManager.GetString("ExcluirFornecedor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove product.
        /// </summary>
        internal static string ExcluirProduto {
            get {
                return ResourceManager.GetString("ExcluirProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove sale.
        /// </summary>
        internal static string ExcluirVenda {
            get {
                return ResourceManager.GetString("ExcluirVenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers.
        /// </summary>
        internal static string Fornecedores {
            get {
                return ResourceManager.GetString("Fornecedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List suppliers.
        /// </summary>
        internal static string ListarFornecedores {
            get {
                return ResourceManager.GetString("ListarFornecedores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List products.
        /// </summary>
        internal static string ListarProdutos {
            get {
                return ResourceManager.GetString("ListarProdutos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List sales.
        /// </summary>
        internal static string ListarVendas {
            get {
                return ResourceManager.GetString("ListarVendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Option.
        /// </summary>
        internal static string OpçãoInvalida {
            get {
                return ResourceManager.GetString("OpçãoInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        internal static string Produtos {
            get {
                return ResourceManager.GetString("Produtos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Sair {
            get {
                return ResourceManager.GetString("Sair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose an option:.
        /// </summary>
        internal static string SelecioneOpcaoMenu {
            get {
                return ResourceManager.GetString("SelecioneOpcaoMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string Vendas {
            get {
                return ResourceManager.GetString("Vendas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go back.
        /// </summary>
        internal static string Voltar {
            get {
                return ResourceManager.GetString("Voltar", resourceCulture);
            }
        }
    }
}
